//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStore.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int BeerID { get; set; }
        public int BeerStyleID { get; set; }
        public string BeerName { get; set; }
        public string BeerDesc { get; set; }
        public string ABV { get; set; }
        public string BeerImage { get; set; }
        public int StatusID { get; set; }
        public int PkgID { get; set; }
    
        public virtual BeerStyle BeerStyle { get; set; }
        public virtual Package Package { get; set; }
        public virtual Status Status { get; set; }
    }
}
